### ISSUE TITLE
Location query not persisted

### ISSUE THREAD

**Issue by ghost** [linksmart/grafana-sensorthings-datasource#1]
<p>Steps to reproduce:</p>
<ol>
	<li>Add a query to Worldmap panel</li>
	<li>Close editor</li>
	<li>Save and refresh</li>
	<li>Go to editor -> query is empty</li>
</ol>

<i>[LS-492] created by tavakoli</i>

**Comment by farshidtz** [comment]
Not sure if still an issue. Will close.
