### ISSUE TITLE
Decide about the Location encodingType

### ISSUE THREAD

**Issue by ghost** [linksmart/grafana-sensorthings-datasource#16]
<p> </p>

<p> </p>

<p><b>The location object is represented differently with the same encodingType. We should find out which one is the correct format.</b></p>

<p><a href="http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#26" class="external-link" rel="nofollow">http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#26</a></p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>{
"encodingType":"application/vnd.geo+json",
"name":"CCIT",
"description":"Calgary Center for Innvative Technologies",
  "location":{
    "type":"Feature",
    "geometry":{
      "type":"Point",
      "coordinates":[
-114.06,
51.05
      ]
    }
  }
}</pre>
</div></div>
<p> </p>

<p><a href="http://developers.sensorup.com/docs/" class="external-link" rel="nofollow">http://developers.sensorup.com/docs/</a></p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>{ 
  "name": "UofC CCIT",  
  "description": "University of Calgary, CCIT building", 
  "encodingType": "application/vnd.geo+json", 
  "location": { 
    "type": "Point", 
    "coordinates": [-114.133, 51.08] 
  }
}
</pre>
</div></div>
<p> </p>

<p> </p>
<i>[LS-345] created by tavakoli</i>

**Comment by farshidtz** [comment]
According to [RFC7946](https://tools.ietf.org/html/rfc7946#section-1.5), the location object should have the following format for points:

```
{
   "type":"Feature",
   "geometry":{
      "type":"Point",
      "coordinates":[
         102.0,
         0.5
      ]
   },
   "properties":{
      "prop0":"value0"
   }
}
```

**Comment by farshidtz** [comment]
Version v1.3.0 supports both formats.
