### ISSUE TITLE
Error when adding Thing to worldmap panel

### ISSUE THREAD

**Issue by gamesbook** [linksmart/grafana-sensorthings-datasource#26]
When trying to configure the worldmap panel with a new Thing, which has a single historical location, it does not display.

The `!` error alert on the panel reports:

`Cannot read property '0' of undefined`

The  Query Inspector button appear to work and shows the correct location data (a single point) retrieved from the SensorThings API.

Below is screenshot of panel in edit mode:

![Screenshot from 2019-08-02 09-56-58](https://user-images.githubusercontent.com/354027/62362572-8ca7d880-b51d-11e9-8f04-a64ecf70a884.png)

**Comment by farshidtz** [comment]
Hi, 

Thank you for reporting the issue. It seems like you are using a different (and correct) representation of GeoJson Point. Please see #16, the plugin expects the second format. We will submit a fix soon.
