### ISSUE TITLE
unordered response

### ISSUE THREAD

**Issue by ThomasKurz** [linksmart/grafana-sensorthings-datasource#29]
When requesting data from [Frost STA Server](https://github.com/FraunhoferIOSB/FROST-Server) the timestamps sometimes jump back and forth, which leads to strange diagrams...

Adding `&$orderby=phenomenonTime desc` to the query avoids this.

**Comment by Niklas345** [comment]
Hey, we're working with the FROST Implementation, too, and are facing the same small issue. Getting the PR approved and released would be greatly appreciated!

**Comment by farshidtz** [comment]
Thanks a lot. The PR is merged now. 

I will close this issue and draft a new release.
