### ISSUE TITLE
Use JSONPath when SensorThingsAPI Observation contains an Object as result

### ISSUE THREAD

**Issue by BWibo** [linksmart/grafana-sensorthings-datasource#33]
Hey there, 

I am querying OGC SensorThingsAPI Observations from a FROST-Server instance. That works fine, if the `result` property contains a numeric value. I am wondering if it is possible to query data using JSONPath when the `result` property contains an  object as shown in the example below. The JSONPath I imagine looks e.g. like this: `$.response.value[*].result.x`. According to https://jsonpath.com/ this should work. I tried several variations of the JSONPath but I was not able to get it working. 

Am I doing something wrong or is this generally not possible? Are JSONPath queries only applicable to `result` properties according to OM_Observation, as described here:  #8 

```json
{
  "request": {
    "url": "api/datasources/proxy/1/Datastreams(102)/Observations?$filter=phenomenonTime gt 2020-06-24T10:50:08.950Z and phenomenonTime lt 2020-07-24T10:50:08.950Z&$select=phenomenonTime,result&$top=1000",
    "method": "GET"
  },
  "response": {
    "value": [
      {
        "phenomenonTime": "2020-07-21T09:52:05.062Z",
        "result": {
          "x": 1,
          "y": 2,
          "z": 3
        }
      },
      {
        "phenomenonTime": "2020-07-21T09:54:14.962Z",
        "result": {
          "x": 6,
          "y": 6,
          "z": 6
        }
      }
    ]
  }
}
```

```text
Version info:
 - Grafana v7.0.3 (00ee734baf)
 - Grafana OGC SensorThings Plugin v1.3.0
```

Thanks in advance.

**Comment by farshidtz** [comment]
Hi,

Looks like the response you are getting from the server is different than the specs. See e.g.:
https://developers.sensorup.com/docs/#observations_get

In your example, the object is wrapped inside "result". But OGC SensorThings plugin expects:
```json
{
    "value": [
      {
        "phenomenonTime": "2020-07-21T09:52:05.062Z",
        "result": {
          "x": 1,
          "y": 2,
          "z": 3
        }
      },
      {
        "phenomenonTime": "2020-07-21T09:54:14.962Z",
        "result": {
          "x": 6,
          "y": 6,
          "z": 6
        }
      }
    ]
}
```

With that, the JSONPath would be `$.x`.

**Comment by BWibo** [comment]
Hey there, it works using `$.x` as JSONPath expression. Thank you!
