### ISSUE TITLE
Compatibility with Grafana 7 and Worldmap Panel v0.3.x

### ISSUE THREAD

**Issue by farshidtz** [linksmart/grafana-sensorthings-datasource#40]
Grafana Worldmap Panel has been updates and is now apparently compatible with Grafana 7: https://github.com/grafana/worldmap-panel/releases

We switched to using [Grafana Map Panel](https://github.com/panodata/grafana-map-panel) because Grafana Worldmap Panel wasn't working. But seems like Grafana Map Panel is not working either (see #35).

Here is our old readme with instructions how to configure Grafana Worldmap Panel: https://github.com/linksmart/grafana-sensorthings-datasource/tree/v1.3.0#world-map-view

We should be able to pass location data to Grafana Worldmap Panel as "JSON results" input. The query area used to list Things and give location data only on map panel type (see the GIF [here](https://github.com/linksmart/grafana-sensorthings-datasource/tree/v1.3.0#world-map-view)). But Grafana 7 has changed and panel in now selectable after query configuration. There is currently no way to select location data because the query area doesn't respond to change of panel to map.

I am thinking we can simply add `HistoricalLocations-><list of things>` to this list and show it for all panel types:
![image](https://user-images.githubusercontent.com/11150423/92998872-db93b000-f51c-11ea-8908-add329306d56.png)

**Comment by blubbfish** [comment]
As inspecting this issue, the only possibility to get this running for now, is to tranfer the data as "table". It seems that worldmap has an issue or some misunderstanding of grafana internals, so they expecting data in a wrong format for `json result`.

It's not a nice solution but it seems that it can run with worldmap again.
