### ISSUE TITLE
plugins not working with grafana v8.1.2

### ISSUE THREAD

**Issue by chenkianwee** [linksmart/grafana-sensorthings-datasource#59]
Hi I am using grafana 8.1.2 with the plugin and I cannot get the plugin to work

**Comment by Okanmercan99** [comment]
> Hi I am using grafana 8.1.2 with the plugin and I cannot get the plugin to work

8.x.x versions do not work currently. 7.5.10 version is working.

**Comment by farshidtz** [comment]
Hi,

Thank you for reporting. Please note that the plugin is now maintained at https://github.com/FraunhoferIOSB/frost-sensorthings-datasource

You may follow this issue: https://github.com/FraunhoferIOSB/frost-sensorthings-datasource/issues/6
